version: "3.9"
services:
  postgres:
    env_file: .env
    image: "${pgsl_version}"
    environment:
      POSTGRES_DB: "${db_name}"
      POSTGRES_USER: "${user_name}"
      POSTGRES_PASSWORD: "${user_pass}"
      PGDATA: "/usr/share/postgres/bases"
    ports:
      - "5432:5432"
    volumes:
      - ${data_path}:/usr/share/postgres
    restart: unless-stopped

  pgadmin:
    env_file: .env
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${admin_email}"
      PGADMIN_DEFAULT_PASSWORD: "${admin_pass}"
    ports:
      - "${admin_port}:80"


