version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_pass

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3366:80
    environment:
      - PMA_ARBITRARY=1