# Generated by Django 4.2.3 on 2023-07-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotlytest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'invoices_out_table',
                'managed': False,
            },
        ),
    ]
