version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "capdb"
      POSTGRES_USER: "capuser"
      POSTGRES_PASSWORD: "capuser_pass"
      PGDATA: "/usr/share/postgres/bases"
    ports:
      - "5434:5432"



