version: "3.9"
services:
  postgres:
    env_file: .env
    image: "${pgsl_version}"
    environment:
      POSTGRES_DB: "${db_name}"
      POSTGRES_USER: "${user_name}"
      POSTGRES_PASSWORD: "${user_pass}"
      PGDATA: "/usr/share/postgres/bases"
    ports:
      - "${port}:5432"
    volumes:
      - ${data_path}:/usr/share/postgres
    restart: unless-stopped
