version: "1"

services:
  flask_server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_TOKEN=${FLASK_TOKEN}
    networks:
      default: null
    volumes:
      - ../config:/app/config:rw
    ports:
      - "5000:5000"
    restart: always

networks:
  default:
    name: flask_docker_default
