version: "1"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_TOKEN=${FLASK_TOKEN}
    ports:
      - "5000:5000"
    restart: always