version: "2"

services:
  socket_server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SOC_SERVER_PORT=${SOC_SERVER_PORT}
      - SOC_PING_TIME=${SOC_PING_TIME}
    networks:
      default: null
    ports:
      - ${SOC_SERVER_PORT}:${SOC_SERVER_PORT}
    restart: always

